language: android

android:
  components:
    - tools
    - build-tool-26.0.1
    - tools
    - platform-tools
    - android-26
  licenses:
      - ".+"

branches:
  only:
  - master

install:
  - echo y | android update sdk -u -a -t tools
  - echo y | android update sdk -u -a -t platform-tools
  - echo y | android update sdk -u -a -t build-tools-26.0.1
  - echo y | android update sdk -u -a -t android-26
  - echo y | android update sdk -u -a -t extra-google-m2repository
  - echo y | android update sdk -u -a -t extra-android-m2repository
