language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - tools
    - platform-tools
    - build-tool-26.0.1
    - android-26
    - extra-google-m2repository
licenses:
  - ".+"

script:
  - ./gradlew build

branches:
  only:
    - master
